version: '3.9'
services:
  api:
    build: ./server
    environment:
      - REPO_PATH=/data/repo
      - DEFAULT_BRANCH=main
      - REQUIRE_SIGNED_MERGES=true
    volumes:
      - ./repo:/data/repo
    ports:
      - "8080:8080"

  web:
    build: ./web
    environment:
      - VITE_API_BASE=http://localhost:8080
    ports:
      - "5173:4173"
    depends_on:
      - api
